### PR TITLE
u need to merge to dev first dummi uwu

### PR DESCRIPTION
**Pull request by tomstark99**
xddd accept this one too cuz working -> dev then dev -> main

omar rookie mistake

### CODE REVIEW

**Review by omarinio — APPROVED** [review]
why do we need 3 branches xd

**Review by calumwestt — APPROVED** [review]
dummy thicc

**Review by robertpop99 — APPROVED** [review]
(played for 1000 hours)
Played for a bit, was alright

**Review by valispartanu — APPROVED** [review]

**Review by stefanpruna — APPROVED** [review]
Pretty decent buut the text actuially sais sample text so im not sure if i should aprove

**Pull request merged**
