### PR TITLE
alie try again with guards fixed (photon tings)

### PR DESCRIPTION
**Pull request by tomstark99**

### CODE REVIEW

**Review by valispartanu — DISMISSED** [review]

**Review by omarinio — DISMISSED** [review]
stef told me it calm

**Review by robertpop99 — APPROVED** [review]
Can you use some meaningful fking commit messages?

**Review by omarinio — APPROVED** [review]
yep

**Review by stefanpruna — APPROVED** [review]
I agree. Pull requests commits should have meaningful titles

**Review by dANW34V3R — APPROVED** [review]

**Review by calumwestt — APPROVED** [review]
Looks good :)

**Pull request merged**
