### PR TITLE
Working

### PR DESCRIPTION
**Pull request by tomstark99**

### CODE REVIEW

**Review by tomstark99 — COMMENTED** [review]
Very good code I must admit

**Review by calumwestt — APPROVED** [review]

**Review by valispartanu — APPROVED** [review]

**Review by omarinio — APPROVED** [review]
i dont think i've seen a jumpier pull request, approved

**Review by dANW34V3R — APPROVED** [review]
Didn't read

**Review by robertpop99 — APPROVED** [review]
I'll trust that you know what you're commiting, I'm not going to read 126,510 lines

**Pull request merged**
